name: Selenium Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Start Selenium Grid
        run: docker compose up -d

      - name: Wait for Selenium Grid
        run: |
          echo "Waiting for Selenium Grid..."

          for i in {1..30}; do
            if curl -sf http://localhost:4444/status > /dev/null; then
              echo "Selenium Grid is ready!"
              break
            fi

            echo "Grid not ready yet..."
            sleep 2
          done

      - name: Check Selenium Grid
        run: |
          curl -s http://localhost:4444/status

      - name: Show running containers
        run: |
          docker compose ps

      - name: Run Selenium tests
        run: |
          mvn clean test

      - name: Show Docker logs if tests fail
        if: failure()
        run: |
          docker compose logs --tail=200

      - name: Stop Selenium Grid
        if: always()
        run: |
          docker compose down